### ISSUE TITLE
test-samples/Fts.pem is apparently bogus

### ISSUE THREAD

**Issue by chmike** [ayllon/go-proxy#2]
When I try to display the content of each certificate in `test-samples/Fts.pem` with openssl, I get an error when trying to display the last certificate which I expect is the end user certificate. 

The next level certificate has also some weird content. Don’t know if it is correct and expected. 

I thus suspect that this certificate is in some way bogus. May we drop it ?

**Comment by ayllon** [comment]
There was a missing dash at the end of Fts.pem
I guess the x509 library used to be fine with it, but now it is more picky (as it should, in fact).
go test works for me now. Can you give it a try?

**Comment by chmike** [comment]
The tests now pass without an error. Thank you. Your package is fully operational again.
